Pertama import Library

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
df = pd.read_csv('resto_preprocessed.csv', delimiter=';', header=0)

In [3]:
print(df)

       Avg Spend Level  District  subdistrict  Highest Price  Lowest Price  \
0                    1        11           67        1400000          3000   
1                    2        11           67          65000          2000   
2                    2        11           67          48000          3000   
3                    1        11          142          18300          3500   
4                    2        10           89          35000          4000   
...                ...       ...          ...            ...           ...   
25126                2        14          145         120000          4000   
25127                1         8          119          61000          5200   
25128                3         8          119         152004          2000   
25129                2         4          143          82500          3500   
25130                1        11           14          35000          4500   

       Average Price  Popularity  Category_Aneka nasi  Category

Merubah dataframe menjadi array numpy

In [4]:
df = df.to_numpy()
print(df)

[[  1  11  67 ...   0   0   0]
 [  2  11  67 ...   0   0   0]
 [  2  11  67 ...   0   0   0]
 ...
 [  3   8 119 ...   0   0   0]
 [  2   4 143 ...   0   0   0]
 [  1  11  14 ...   0   0   0]]


Membagi 80% data untuk data Training dan 20% untuk dataTesting

In [10]:
split_index = int(0.8 * len(df))
dataTraining = df[:split_index, :]
dataTesting = df[split_index:, :]
print(dataTraining)
print(dataTesting)

[[  1  11  67 ...   0   0   0]
 [  2  11  67 ...   0   0   0]
 [  2  11  67 ...   0   0   0]
 ...
 [  1  14  81 ...   0   0   0]
 [  2   3 146 ...   0   0   0]
 [  2   3 136 ...   0   0   0]]
[[  1   8  47 ...   0   0   0]
 [  2  14 137 ...   0   0   0]
 [  1  14 145 ...   0   0   0]
 ...
 [  3   8 119 ...   0   0   0]
 [  2   4 143 ...   0   0   0]
 [  1  11  14 ...   0   0   0]]


In [13]:
# 80% untuk dataTraining
# 20% untuk dataTesting
print(len(dataTraining))
print(len(dataTesting))

20104
5027


Menjadikan District, Subdistrict, Average Price sebagai input
dan labelnya adalah popularity

In [29]:
# District, Subdistrict, Average Price (Input)
inputTraining = dataTraining[:, [1, 2, 5]]
inputTesting = dataTesting[:, [1, 2, 5]]
# Popularity (Label)
labelTraining = dataTraining[:, 6]
labelTesting = dataTesting[:, 6]

In [30]:
model = tree.DecisionTreeClassifier()


In [31]:
model = model.fit(inputTraining, labelTraining)


In [32]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [2 0 2 ... 0 0 0]
Hasil Prediksi :  [2 0 2 ... 0 0 0]


In [34]:

prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, "data")
print("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi Benar :  4726 data
Prediksi Salah :  301 data
Akurasi :  94.01233339964193 %
